version: 2.1
jobs:
  test3_11:
    docker: &main-version
      - image: cimg/python:3.11.3
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps: &test-steps
      - checkout
      - run:
          name: Install
          command: |
            pip install numpy ipython mock pytest
            sudo apt -y update && sudo apt -y install bats
            sh tests/install_for_dev.sh
      - run: 
          name: DocTest
          command: python -m doctest shape_commentator/main.py
      - run:
          name: BatsTest
          command: bats tests/test_all.bats
  test3_10:
    docker:
        - image: cimg/python:3.10.11
          auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps: *test-steps
  test3_9:
    docker:
        - image: cimg/python:3.9.16
          auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps: *test-steps
  test3_8:
    docker:
        - image: cimg/python:3.8.16
          auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps: *test-steps
  test3_7:
    docker:
        - image: cimg/python:3.7.16
          auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps: *test-steps
  test3_6:
    docker:
        - image: cimg/python:3.6.15
          auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps: *test-steps
  test3_5:
    docker:
        - image: cimg/python:3.5.10
          auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps: *test-steps
  test2_7:
    docker:
        - image: cimg/python:2.7.18
          auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps: *test-steps
  deploy:
    docker: *main-version
    steps:
      - checkout
      - run:
          name: Install
          command: pip install twine
      - run:
          name: PyPI
          command: |
            python setup.py sdist
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository=https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username = shiba6v" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            twine upload --repository pypi dist/*
workflows:
  version: 2
  build-and-test:
    jobs:
      - test3_11
      - test3_10
      - test3_9
      - test3_8
      - test3_7
      - test3_6
      - test3_5
      - test2_7
      - deploy:
          filters:
              branches:
                  ignore: /.*/
              tags:
                  only: /^v_.*/