version: 2.1
jobs:
  test36:
    docker:
      - image: circleci/python:3.6.6
    steps: &test-steps
      - checkout
      - run:
          name: Install
          command: |
            sudo pip install numpy ipython
            sudo apt install bats
            sudo sh tests/install_for_dev.sh
      - run: 
          name: DocTest
          command: python -m doctest shape_commentator/main.py
      - run:
          name: BatsTest
          command: bats tests/test_all.bats
  test35:
    docker:
        - image: circleci/python:3.5.6
    steps: *test-steps
  test34:
    docker:
        - image: circleci/python:3.4.9
    steps: *test-steps
  test27:
    docker:
        - image: circleci/python:2.7.15
    steps: *test-steps
  deploy:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install twine
      - run:
          name: PyPI
          command: |
            python setup.py sdist
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository=https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username = shiba6v" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            twine upload --repository pypi dist/*
workflows:
  version: 2
  build-and-test:
    jobs:
      - test36:
          filters: &filters-test
              tags:
                  only: /^v_.*/
      - test35:
          filters:
              *filters-test
      - test34:
          filters:
              *filters-test
      - test27:
          filters:
              *filters-test
      - deploy:
          requires: &all-version-requirements
            - test36
            - test35
            - test34
            - test27
          filters:
              branches:
                  ignore: /.*/
              tags:
                  only: /^v_.*/