version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install numpy
      - run: 
          name: Tests
          command: python -m doctest shape_commentator/shape_commentator.py
  deploy-test:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install twine
      - run:
          name: TestPyPI
          command: |
            python setup.py sdist
            echo -e "[testpypi]" >> ~/.pypirc
            echo -e "repository=https://test.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username = shiba6v" >> ~/.pypirc
            echo -e "password = $TESTPYPI_PASSWORD" >> ~/.pypirc
            twine upload --repository testpypi dist/*
  deploy:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Install
          command: sudo pip install twine
      - run:
          name: PyPI
          command: |
            python setup.py sdist
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository=https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username = shiba6v" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            twine upload --repository pypi dist/*
workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - deploy-test:
          requires:
            - test
          filters:
              branches:
                  only:
                    - master
      - deploy:
          requires:
            - test
          filters:
              tags:
                  only:
                    - /^v_.*/